// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhXbNx0bb9IOk_MtFGrkc96glFdxUqks',
    appId: '1:395036848681:web:c017863efb08d1df2ea238',
    messagingSenderId: '395036848681',
    projectId: 'fitfit-login',
    authDomain: 'fitfit-login.firebaseapp.com',
    storageBucket: 'fitfit-login.appspot.com',
    measurementId: 'G-9B41X2PSGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEThA826COSs2nd6479rKHj4cJr0CCdx8',
    appId: '1:395036848681:android:f023cefcfed95ed62ea238',
    messagingSenderId: '395036848681',
    projectId: 'fitfit-login',
    storageBucket: 'fitfit-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFBKjZ0lxDUhPoe0rOxJYniFlNNBELjQ',
    appId: '1:395036848681:ios:b82b7e75e72b37c82ea238',
    messagingSenderId: '395036848681',
    projectId: 'fitfit-login',
    storageBucket: 'fitfit-login.appspot.com',
    iosBundleId: 'com.example.frontendFitfitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFBKjZ0lxDUhPoe0rOxJYniFlNNBELjQ',
    appId: '1:395036848681:ios:4350aa5fdfd4eb342ea238',
    messagingSenderId: '395036848681',
    projectId: 'fitfit-login',
    storageBucket: 'fitfit-login.appspot.com',
    iosBundleId: 'com.example.frontendFitfitApp.RunnerTests',
  );
}
